# Generated by Django 3.2.9 on 2021-11-07 12:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=100, verbose_name='場所')),
                ('cycle', models.IntegerField(verbose_name='周期')),
                ('cleanup_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='清掃日')),
            ],
        ),
    ]
