# Generated by Django 2.2.24 on 2021-11-08 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kajumaru', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='state',
            field=models.IntegerField(choices=[(1, 'happy'), (2, 'normal'), (3, 'danger'), (4, 'angry')], default=2),
        ),
    ]
